### ISSUE TITLE
Register API accepts any password

### ISSUE THREAD

**Issue by Vitroxyn** [TheMorpheus407/BattleOfAI#7]
# Issue
It is possible to register a new user with an arbitrary password via the [register API](https://iam.battleofai.net/api/iam/register).

# Vulnerabilities

- The password is not meeting the standards, you could even use an empty password. This makes attacks like brute-force easier.
- The password is not protected against man-in-the-middle attacks.

# Solution
The API should only allow hashed strings as password.

**Comment by TheMorpheus407** [comment]
Fixed, thanks. Although I did not hash the password on the client side.
Against MitM there is https.
If the pws were hashed on client side, the hashes of the password instead of the password itself would be the real password. So if an attacker gains access to the database, he owns any password. That's why they have to be hashed serverside
